name: CloudFormation Nag Scan

on: [push]

jobs:
  cfn-nag-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simple test
        uses: stelligent/cfn_nag@master
        with:
          input_path: ./templates
